name: Deploy Matrix Bot

on:
  push:
    branches:
      - main # or the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Run Matrix Bot
      run: node dist/basic-bot.js
