name: Deploy Matrix Bot

on:
  push:
    branches:
      - main # or the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DeployBot

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    # - name: Obtain BOT-ACCESS-TOKEN
    #   id: get_bot_access_token
    #   run: node dist/bot-login.js

    # - name: Set BOT_ACCESS_TOKEN as a secret
    #   run: echo "BOT_ACCESS_TOKEN=${{ env.BOT_ACCESS_TOKEN }}" >> $GITHUB_ENV

    - name: Run Matrix Bot
      run: node dist/basic-bot.js

